spring:
  config:
    activate:
      on-profile: "production"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  web:
    server:
      port: ${PORT:8080}
      address: 0.0.0.0

# SpringDoc для production (можно отключить UI если нужно)
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

sentry:
  dsn: https://82bb966831abe9f39d493b357ac696a5@o4510283776327680.ingest.de.sentry.io/4510283784978512
  environment: production
  send-default-pii: true
  tracing:
    enabled: true
    traces-sample-rate: 1.0
  exception-resolver-order: -10  # Ensure Sentry runs before custom exception handlers