spring:
  config:
    activate:
      on-profile: "development"
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

# SpringDoc для development
springdoc:
  swagger-ui:
    enabled: true