spring:
  config:
    activate:
      on-profile: "production"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  web:
    server:
      port: ${PORT:8080}
      address: 0.0.0.0

# SpringDoc для production (можно отключить UI если нужно)
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true