spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

logging:
  level:
    com.yourpackage: DEBUG
    org.springframework.jdbc: DEBUG
    org.hibernate: INFO